[package]
name = "fugle"
version = "0.2.2"
authors = ["tommady <tommady@users.noreply.github.com>"]
description = "A Simple, Lightweight, Fast and Safe Fugle Library"
license = "MIT"
readme = "README.md"
homepage = "https://github.com/tommady/fugle-rs"
repository = "https://github.com/tommady/fugle-rs"
keywords = ["fugle", "stock"]
categories = ["web-programming::http-client", "web-programming::websocket"]
edition = "2018"

[features]
default = []
websocket = ["tungstenite", "log"]

[package.metadata.docs.rs]
features = ["websocket"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
log = { version = "0.4", optional = true }
# ureq using tls as default  feature which is rustls by default
ureq = { version = "2.1", features = ["json"] }

[dependencies.tungstenite]
# TODO: waiting the author to publish new tag
# should use the newest master branch which merged this PR
# https://github.com/snapview/tungstenite-rs/pull/205
version = "0.13"
default-features = false
features = ["rustls-tls"]
optional = true
