[package]
name = "fugle"
version = "0.2.0"
authors = ["tommady <tommady@users.noreply.github.com>"]
description = "A Simple, Lightweight, Fast and Safe Fugle Library"
license-file = "MIT"
readme = "README.md"
homepage = "https://github.com/tommady/fugle-rs"
repository = "https://github.com/tommady/fugle-rs"
keywords = ["fugle", "stock"]
categories = ["web-programming::http-client", "web-programming::websocket"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
log = "0.4"

# tungstenite on the current version 0.13,
# if disable default but it still using native-tls in somewhere so it causing 
# compile dependency still have 
# * openssl
# * native-tls
# * openssl-sys
# but if change to use the master branch, it will compile failed by
# using old rustls with new webpki and new webpki-roots
# TODO: wait for the new version to see if this issue fixed
# tungstenite = { version = "0.13", default-futures = false, features = ["rustls-tls"] }
tungstenite = { version = "0.13", features = ["rustls-tls"] }

# ureq using tls as default  feature which is rustls by default
ureq = { version = "2.1", features = ["json"] }
