[package]
name = "fugle"
version = "0.2.0"
authors = ["tommady <tommady@users.noreply.github.com>"]
description = "a rust library of https://developer.fugle.tw"
license-file = "LICENSE"
readme = "README.md"
homepage = "https://github.com/tommady/fugle-rs"
repository = "https://github.com/tommady/fugle-rs"
keywords = ["fugle", "stock"]
categories = ["web-programming::http-client", "web-programming::websocket"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
log = "0.4"
tungstenite = { version = "0.13", default-futures = false, features = ["native-tls"] }
ureq = { version = "2.1", default-futures = false, features = ["json", "native-certs"] }
