[package]
name = "fugle"
version = "0.3.4"
authors = ["tommady <tommady@users.noreply.github.com>"]
description = "A Simple, Lightweight, Fast and Safe Fugle Library"
license = "MIT"
readme = "README.md"
homepage = "https://github.com/tommady/fugle-rs"
repository = "https://github.com/tommady/fugle-rs"
keywords = ["fugle", "stock"]
categories = ["web-programming::http-client", "web-programming::websocket"]
edition = "2021"

[features]
default = []
websocket = ["tungstenite", "log"]

[package.metadata.docs.rs]
features = ["websocket"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
ureq = { version = "2.3", features = ["json"] }
log = { version = "0.4", optional = true }

[dependencies.tungstenite]
version = "0.16"
default-features = false
features = ["rustls-tls-native-roots"]
optional = true
