[package]
name = "fugle"
version = "0.1.1"
authors = ["tommady <tommady@users.noreply.github.com>"]
description = "a rust library of https://developer.fugle.tw"
license-file = "LICENSE"
readme = "README.md"
homepage = "https://github.com/tommady/fugle-rs"
repository = "https://github.com/tommady/fugle-rs"
keywords = ["fugle", "stock"]
categories = ["web-programming::http-client", "web-programming::websocket"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
serde = { version = "1.0.110", features = ["derive"] }
chrono = { version = "0.4.11", features = ["serde"] }
reqwest = { version = "0.10.4", features = ["blocking", "json"] }
tungstenite = { version = "0.10.1", features = ["tls"] }
serde_json = "1.0.53"
log = "0.4.8"
pretty_env_logger = "0.4.0"
native-tls = "0.2.4"
