name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [1.56.0]
    steps:
    - uses: actions/checkout@v2
    - name: Check Formatting
      run: cargo fmt --all -- --check 
    - name: Check Clippy Lints 
      run: cargo clippy --all-targets --all-features -- -D warnings 
  
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [1.56.0]
    steps:
    - uses: actions/checkout@v2
    - name: Run Tests 
      run: cargo test --all --all-features --no-fail-fast
